# Generated by Django 2.1.7 on 2019-03-12 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freeshelfapp', '0003_auto_20190312_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='picture',
            field=models.ImageField(null=True, upload_to='books/'),
        ),
    ]
