# Generated by Django 2.1.7 on 2019-03-12 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freeshelfapp', '0006_auto_20190312_1722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(to='freeshelfapp.Author'),
        ),
    ]
