# Generated by Django 2.1.7 on 2019-03-15 11:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('freeshelfapp', '0008_auto_20190314_0652'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='favorited_by',
            field=models.ManyToManyField(related_name='favorite_books', through='freeshelfapp.Favorite', to=settings.AUTH_USER_MODEL),
        ),
    ]
