# Generated by Django 2.1.7 on 2019-03-15 18:31

# started by running '$ ./manage.py makemigrations --empty freeshelfapp'

# '$ ./manage.py makemigrations --empty freeshelfapp' added this by default
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freeshelfapp', '0009_book_favorited_by'),
    ]

    operations = [
    ]
