# Generated by Django 2.1.7 on 2019-03-17 09:46
# see migration 0012 for a full explanation
# adding picture field in this migration

from django.db import migrations
import csv
import os.path
from django.conf import settings
from django.core.files import File

def load_book_data(apps, schema_editor):
    """
    Read a CSV file full of books and insert them into the database
    """
    Book = apps.get_model('freeshelfapp', 'Book')

    datapath = os.path.join(settings.BASE_DIR, 'initial_data')
    datafile = os.path.join(datapath, 'books.csv')

    with open(datafile) as file: 
        reader = csv.DictReader(file)
        for row in reader:
            book_title = row['title']
            if Book.objects.filter(title=book_title).count:
                Book.objects.filter(title=book_title).delete()
            book = Book(
                title=row['title'],
                summary=row['summary'],
                url=row['url'],
            )
            book.save()
        
            if row['picture'] == '':
                continue
            book.picture.save(
                row['picture'], 
                File(open(os.path.join(datapath, row['picture']), 'rb'))
            )
                # https://docs.djangoproject.com/en/2.1/ref/files/file/#additional-methods-on-files-attached-to-objects
                # '.save(name, content, save=True)' saves a new file with the file name and contents provided
                # "row['picture']" specifies the file name
                # https://docs.djangoproject.com/en/2.1/topics/files/#the-file-object
                # 'File()' Django built-in function used to create a 'file' object
                # https://docs.python.org/3.7/library/functions.html#open
                # 'open(file, mode)' Python built-in function used to open the "row['picture']" file in 'rb' mode ('rb' stands for open for reading in binary mode)
            book.save()

class Migration(migrations.Migration):

    dependencies = [
        ('freeshelfapp', '0012_auto_20190316_1104'),
    ]

    operations = [
        migrations.RunPython(load_book_data)
    ]
