# Generated by Django 2.1.7 on 2019-03-17 11:26
# see migration 0012 for a full explanation
# adding categories in this migration

from django.db import migrations
import csv
import os.path
from django.conf import settings
from django.core.files import File
from django.utils.text import slugify

def load_category_data(apps, schema_editor):
    """
    Read a CSV file full of categories and insert them into the database
    """
    Category = apps.get_model('freeshelfapp', 'Category')

    datapath = os.path.join(settings.BASE_DIR, 'initial_data')
    datafile = os.path.join(datapath, 'categories.csv')

    with open(datafile) as file: 
        reader = csv.DictReader(file)
        for row in reader:
            category_name = row['name']
            if Category.objects.filter(name=category_name).count():
                continue
            category = Category(
                name=row['name'],
            )
            category.save()
            if row['slug'] == '':
                base_slug = slugify(row['name'])
                slug = base_slug
                n = 0
                while Category.objects.filter(slug=slug).count():
                    n += 1
                    slug = base_slug + "-" + str(n)
                category.slug = slug
            category.save()
            
class Migration(migrations.Migration):

    dependencies = [
        ('freeshelfapp', '0013_auto_20190317_0546'),
    ]

    operations = [
        migrations.RunPython(load_category_data)
    ]
